openapi: 3.0.1
info:
  title: Sales and Tax Payment Service
  description: API for sending sales and tax payment events, querying tax positions, and amending sales.
  version: 1.0.0
paths:
  /transactions:
    post:
      summary: Ingest sales and tax payment events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SaleEvent'
                - $ref: '#/components/schemas/TaxPaymentEvent'
            examples:
              SaleEvent:
                summary: Sale Event Example
                value:
                  eventType: "SALES"
                  date: "2024-02-22T17:29:39Z"
                  invoiceId: "3419027d-960f-4e8f-b8b7-f7b2b4791824"
                  items:
                    - itemId: "02db47b6-fe68-4005-a827-24c6e962f3df"
                      cost: 1099
                      taxRate: 0.2
              TaxPaymentEvent:
                summary: Tax Payment Event Example
                value:
                  eventType: "TAX_PAYMENT"
                  date: "2024-02-22T17:29:39Z"
                  amount: 74901
      responses:
        '202':
          description: Successful response
  /tax-position:
    get:
      summary: Query tax position at a given point in time
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date-time
          required: true
          example: "2024-02-22T17:29:39Z"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxPositionResponse'
              example:
                date: "2024-02-22T17:29:39Z"
                taxPosition: 49
  /sale:
    patch:
      summary: Amend an item within a sale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaleAmendmentEvent'
            examples:
              SaleAmendmentEvent:
                summary: Amend Sale Event Example
                value:
                  date: "2024-02-22T17:29:39Z"
                  invoiceId: "3419027d-960f-4e8f-b8b7-f7b2b4791824"
                  itemId: "02db47b6-fe68-4005-a827-24c6e962f3df"
                  cost: 798
                  taxRate: 0.15
      responses:
        '202':
          description: Successful response
components:
  schemas:
    SaleEvent:
      type: object
      properties:
        eventType:
          type: string
          example: "SALES"
        date:
          type: string
          format: date-time
        invoiceId:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              itemId:
                type: string
              cost:
                type: integer
              taxRate:
                type: number
    TaxPaymentEvent:
      type: object
      properties:
        eventType:
          type: string
          example: "TAX_PAYMENT"
        date:
          type: string
          format: date-time
        amount:
          type: integer
    TaxPositionResponse:
      type: object
      properties:
        date:
          type: string
          format: date-time
        taxPosition:
          type: integer
    SaleAmendmentEvent:
      type: object
      properties:
        date:
          type: string
          format: date-time
        invoiceId:
          type: string
        itemId:
          type: string
        cost:
          type: integer
        taxRate:
          type: number
